version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
  settings:
    exhaustive:
      default-signifies-exhaustive: false
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - hugeParam
        - ifElseChain
        - octalLiteral
        - rangeValCopy
        - unnamedResult
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    paralleltest:
      ignore-missing: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - funlen
          - err113
          - gosec
          - dupl
          - maintidx
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/vladimirkorzhenevskiy/goops)
    goimports:
      local-prefixes:
        - github.com/vladimirkorzhenevskiy/goops
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
